CISCO = "cisco"
HUAWEI = "huawei"

DO_SNMP_TEST = "do_snmp_test"

ENTER_CONFIGURATION_MODE = "enter_configuration_mode"
EXIT_CONFIGURATION_MODE = "exit_configuration_mode"
SETUP_SESSION = "setup_session"
SHOW_SOFTWARE = "show_software"
SHOW_UPTIME = "show_uptime"
SHOW_VERSION = "show_version"
SHOW_HOSTNAME = "show_hostname"
SHOW_SSH_INFO = "show_ssh_info"
SHOW_LICENSE = "show_license_info"
ENABLE = "enable"
ENABLE_WITH_EXPECTED_PROMPT = "enable_with_expected_prompt"
SHOW_RUNNING_CONFIG = "show_running_config"
SHOW_HOST_CONFIGURATION = "show_host_configuration"
SHOW_RUN_IP_ROUTE = "show_run_ip_route"
SHOW_STARTUP_CONFIG = "show_startup_config"
RESET_STARTUP_CONFIG = "reset_startup_config"
REBOOT = "reboot"
REBOOT_IN = "reboot_in"

SHOW_MEMORY_STATISTICS = "show_memory_statistics"
SHOW_FLASH_STATISTICS = "show_flash_statistics"
SHOW_CELLULAR = "show_cellular"
SHOW_CONTROLLER = "show_controller"
SHOW_INVENTORY = "show_inventory"
SHOW_FEATURESET = "show_featureset"
SHOW_DHCP = "show_config_dhcp"

CHANGE_ROUTER_NAME = "change_router_name"

DISPLAY_MD5 = "display_md5"
VERIFY_MD5 = "verify_md5"
SET_BOOT_IOS = "set_boot_ios"
SAVE_CONFIG = "save_config"
SEND_SYSLOG = "send_syslog"
GET_BOOT_STATEMENTS = "get_boot_statements"
LIST_SOFTWARE_FILES = "list_software_files"
DELETE_FILE = "delete_file"
REMOVE_EEM_SSH_SCRIPT = "remove_eem_ssh_script"
